# ~/.config/yazi/yazi.toml
[mgr]
linemode = "size_and_mtime"

[preview]
wrap = "yes"

[opener]
play = [
	{ run = "ffplay %s", orphan = true, for = "unix" },
]
edit = [
	{ run = "$EDITOR %s", block = true, for = "unix" },
]
